/**
 * Script to:
 * 1) Convert all "en" string fields to arrays (single-element where no synonym needed)
 * 2) Add English synonyms for common A1 and A2 Polish words
 */
const fs = require('fs');
const words = JSON.parse(fs.readFileSync('./words.json', 'utf-8'));

// Synonyms map: Polish word -> array of English translations
// Only for A1 and A2 level words that genuinely have multiple common English translations
const synonymsMap = {
  // ===== A1 =====
  // People & family
  "miasto": ["city", "town"],
  "wieś": ["village", "countryside"],
  "chłopiec": ["boy", "lad"],
  "dziewczyna": ["girl", "young woman"],
  "matka": ["mother", "mom"],
  "ojciec": ["father", "dad"],
  "babcia": ["grandmother", "grandma"],
  "dziadek": ["grandfather", "grandpa"],
  "mąż": ["husband", "spouse"],
  "żona": ["wife", "spouse"],
  "imię": ["name", "first name"],
  // Body
  "niebo": ["sky", "heaven"],
  "kamień": ["stone", "rock"],
  "lampa": ["lamp", "light"],
  // Household objects
  "łóżko": ["bed", "bunk"],
  "poduszka": ["pillow", "cushion"],
  "koc": ["blanket", "quilt"],
  "kubek": ["mug", "cup"],
  "talerz": ["plate", "dish"],
  "garnek": ["pot", "saucepan"],
  "butelka": ["bottle", "flask"],
  "szklanka": ["glass", "tumbler"],
  "torba": ["bag", "sack"],
  "parasol": ["umbrella", "brolly"],
  // Home
  "mieszkanie": ["apartment", "flat"],
  "kuchnia": ["kitchen", "cuisine"],
  "łazienka": ["bathroom", "restroom"],
  "sypialnia": ["bedroom", "sleeping room"],
  // Transport
  "samolot": ["airplane", "plane"],
  "rower": ["bicycle", "bike"],
  "motocykl": ["motorcycle", "motorbike"],
  "taksówka": ["taxi", "cab"],
  "statek": ["ship", "vessel"],
  "łódź": ["boat", "vessel"],
  // Places
  "plaża": ["beach", "shore"],
  "wyspa": ["island", "isle"],
  "kościół": ["church", "chapel"],
  "kino": ["cinema", "movie theater"],
  "muzeum": ["museum", "gallery"],
  "szpital": ["hospital", "clinic"],
  // Food & drink
  "makaron": ["pasta", "noodles"],
  "ziemniak": ["potato", "spud"],
  "kurczak": ["chicken", "hen"],
  "ciastko": ["cookie", "biscuit"],
  "ciasto": ["cake", "pastry"],
  "lody": ["ice cream", "gelato"],
  "kanapka": ["sandwich", "sub"],
  "śniadanie": ["breakfast", "morning meal"],
  "kolacja": ["dinner", "supper"],
  "piwo": ["beer", "ale"],
  "sok": ["juice", "fruit juice"],
  "zupa": ["soup", "broth"],
  // Adjectives
  "szary": ["gray", "grey"],
  // Emotions & states
  "uśmiech": ["smile", "grin"],
  "śmiech": ["laughter", "laugh"],
  "krzyk": ["scream", "shout", "yell"],
  "uścisk": ["hug", "embrace"],
  "nadzieja": ["hope", "expectation"],
  "radość": ["joy", "delight"],
  "strach": ["fear", "fright"],
  "smutek": ["sadness", "sorrow"],
  "złość": ["anger", "rage"],
  "odwaga": ["courage", "bravery"],
  "stres": ["stress", "strain"],
  "niepokój": ["anxiety", "worry"],
  "kłótnia": ["argument", "quarrel", "dispute"],
  "żart": ["joke", "jest"],
  "wstyd": ["shame", "embarrassment"],
  "zazdrość": ["jealousy", "envy"],
  "marzenie": ["dream", "wish"],
  "sen": ["sleep", "slumber"],
  "szczęście": ["happiness", "luck", "fortune"],
  // Senses
  "wzrok": ["sight", "vision"],
  "słuch": ["hearing", "sense of hearing"],
  "dotyk": ["touch", "sense of touch"],
  "węch": ["smell", "sense of smell"],
  // Verbs (A1)
  "słyszeć": ["hear", "listen"],
  "trzymać": ["hold", "grasp"],
  "ciąć": ["cut", "slice"],
  "łamać": ["break", "snap"],
  "rysować": ["draw", "sketch"],
  "skakać": ["jump", "leap"],
  "jeździć": ["ride", "travel"],
  "kontynuować": ["continue", "carry on"],
  "powtarzać": ["repeat", "reiterate"],
  "nienawidzić": ["hate", "detest"],
  "preferować": ["prefer", "favor"],
  "wiedzieć": ["know", "be aware of"],
  "studiować": ["study", "learn"],
  "dzwonić": ["call", "phone"],
  "zamawiać": ["order", "book"],
  "mierzyć": ["measure", "gauge"],
  "przedstawiać": ["introduce", "present"],
  "potwierdzać": ["confirm", "verify"],
  "anulować": ["cancel", "call off"],
  "dom": ["house", "home"],
  "duży": ["big", "large"],
  "mały": ["small", "little"],
  "nowy": ["new", "brand new"],
  "stary": ["old", "aged"],
  "dobry": ["good", "fine"],
  "zły": ["bad", "evil", "angry"],
  "piękny": ["beautiful", "pretty", "lovely"],
  "szybki": ["fast", "quick", "rapid"],
  "wolny": ["slow", "free"],
  "drogi": ["expensive", "dear"],
  "tani": ["cheap", "inexpensive"],
  "łatwy": ["easy", "simple"],
  "trudny": ["difficult", "hard"],
  "ciężki": ["heavy", "hard", "difficult"],
  "lekki": ["light", "lightweight"],
  "gorący": ["hot", "boiling"],
  "zimny": ["cold", "chilly"],
  "ciepły": ["warm", "cozy"],
  "młody": ["young", "youthful"],
  "szczęśliwy": ["happy", "lucky"],
  "smutny": ["sad", "unhappy"],
  "głodny": ["hungry", "starving"],
  "zmęczony": ["tired", "exhausted"],
  "chory": ["sick", "ill"],
  "silny": ["strong", "powerful"],
  "słaby": ["weak", "feeble"],
  "ładny": ["nice", "pretty"],
  "brzydki": ["ugly", "unattractive"],
  "czysty": ["clean", "pure"],
  "brudny": ["dirty", "filthy"],
  "mokry": ["wet", "damp"],
  "suchy": ["dry", "arid"],
  "głośny": ["loud", "noisy"],
  "cichy": ["quiet", "silent"],
  "bogaty": ["rich", "wealthy"],
  "biedny": ["poor", "needy"],
  "długi": ["long", "lengthy"],
  "krótki": ["short", "brief"],
  "wysoki": ["tall", "high"],
  "niski": ["low", "short"],
  "szeroki": ["wide", "broad"],
  "wąski": ["narrow", "tight"],
  "gruby": ["thick", "fat"],
  "cienki": ["thin", "slim"],
  "miły": ["nice", "kind", "pleasant"],
  "ważny": ["important", "significant"],
  "prosty": ["simple", "straight"],
  "pusty": ["empty", "vacant"],
  "pełny": ["full", "complete"],
  "prawdziwy": ["true", "real", "genuine"],
  "fałszywy": ["false", "fake"],
  "główny": ["main", "major", "primary"],
  "ostatni": ["last", "final"],
  "pierwszy": ["first", "initial"],
  "następny": ["next", "following"],
  "jedyny": ["only", "sole"],
  "wspólny": ["common", "shared"],
  "dziwny": ["strange", "weird", "odd"],

  // Verbs A1
  "robić": ["do", "make"],
  "mieć": ["have", "own"],
  "iść": ["go", "walk"],
  "jechać": ["go", "drive", "ride"],
  "jeść": ["eat", "have a meal"],
  "pić": ["drink", "have a drink"],
  "widzieć": ["see", "notice"],
  "patrzeć": ["look", "watch"],
  "słuchać": ["listen", "hear"],
  "mówić": ["speak", "say", "talk"],
  "pisać": ["write", "compose"],
  "czytać": ["read", "go through"],
  "uczyć się": ["learn", "study"],
  "pracować": ["work", "labor"],
  "kupować": ["buy", "purchase"],
  "sprzedawać": ["sell", "trade"],
  "dawać": ["give", "hand"],
  "brać": ["take", "grab"],
  "szukać": ["search", "look for"],
  "znajdować": ["find", "discover"],
  "chcieć": ["want", "wish", "desire"],
  "potrzebować": ["need", "require"],
  "lubić": ["like", "enjoy"],
  "kochać": ["love", "adore"],
  "znać": ["know", "be familiar with"],
  "rozumieć": ["understand", "comprehend"],
  "myśleć": ["think", "believe"],
  "pamiętać": ["remember", "recall"],
  "zapominać": ["forget", "overlook"],
  "pomagać": ["help", "assist"],
  "pytać": ["ask", "question"],
  "odpowiadać": ["answer", "reply", "respond"],
  "zaczynać": ["start", "begin"],
  "kończyć": ["finish", "end", "complete"],
  "otwierać": ["open", "unlock"],
  "zamykać": ["close", "shut", "lock"],
  "wchodzić": ["enter", "come in", "go in"],
  "wychodzić": ["leave", "go out", "exit"],
  "wracać": ["return", "come back", "go back"],
  "próbować": ["try", "attempt"],
  "czekać": ["wait", "hold on"],
  "tworzyć": ["create", "make", "form"],
  "naprawiać": ["repair", "fix", "mend"],
  "budować": ["build", "construct"],
  "gotować": ["cook", "prepare"],
  "spać": ["sleep", "rest"],
  "budzić się": ["wake up", "get up"],
  "stać": ["stand", "stop"],
  "siedzieć": ["sit", "be seated"],
  "leżeć": ["lie", "lie down"],
  "biegać": ["run", "jog"],
  "chodzić": ["walk", "go"],
  "pływać": ["swim", "float"],
  "latać": ["fly", "soar"],
  "grać": ["play", "perform"],
  "śpiewać": ["sing", "chant"],
  "tańczyć": ["dance", "move"],
  "płacić": ["pay", "settle"],
  "liczyć": ["count", "calculate"],
  "wierzyć": ["believe", "trust"],
  "nosić": ["carry", "wear"],
  "rzucać": ["throw", "toss"],
  "łapać": ["catch", "grab"],
  "ciągnąć": ["pull", "drag"],
  "pchać": ["push", "shove"],
  "zmieniać": ["change", "alter"],
  "wybierać": ["choose", "pick", "select"],
  "pokazywać": ["show", "display"],
  "ukrywać": ["hide", "conceal"],
  "kłaść": ["put", "lay", "place"],
  "stawiać": ["put", "place", "set"],
  "podnosić": ["lift", "raise", "pick up"],
  "zostawiać": ["leave", "abandon"],
  "tracić": ["lose", "waste"],
  "wygrywać": ["win", "gain"],
  "przegrywać": ["lose", "fail"],
  "uczyć": ["teach", "instruct"],
  "spotykać": ["meet", "encounter"],
  "odwiedzać": ["visit", "call on"],
  "prosić": ["ask", "request"],
  "dziękować": ["thank", "be grateful"],
  "przepraszać": ["apologize", "excuse"],
  "obiecywać": ["promise", "pledge"],
  "pozwalać": ["allow", "let", "permit"],
  "zabraniać": ["forbid", "prohibit"],

  // Nouns A1
  "droga": ["road", "way", "path"],
  "ulica": ["street", "road"],
  "miejsce": ["place", "spot", "seat"],
  "sklep": ["shop", "store"],
  "szkoła": ["school", "academy"],
  "praca": ["work", "job"],
  "pieniądze": ["money", "cash"],
  "czas": ["time", "period"],
  "dzień": ["day", "daytime"],
  "noc": ["night", "nighttime"],
  "rano": ["morning", "dawn"],
  "wieczór": ["evening", "dusk"],
  "rok": ["year", "annum"],
  "jedzenie": ["food", "meal"],
  "samochód": ["car", "automobile"],
  "autobus": ["bus", "coach"],
  "pociąg": ["train", "railway"],
  "film": ["movie", "film"],
  "książka": ["book", "novel"],
  "muzyka": ["music", "tune"],
  "obraz": ["picture", "painting", "image"],
  "prezent": ["gift", "present"],
  "pomysł": ["idea", "thought"],
  "problem": ["problem", "issue", "trouble"],
  "odpowiedź": ["answer", "reply", "response"],
  "pytanie": ["question", "query"],
  "błąd": ["mistake", "error"],
  "początek": ["beginning", "start"],
  "koniec": ["end", "finish"],
  "część": ["part", "piece"],
  "historia": ["history", "story"],
  "pogoda": ["weather", "climate"],
  "słońce": ["sun", "sunshine"],
  "deszcz": ["rain", "rainfall"],
  "wiatr": ["wind", "breeze"],
  "ogień": ["fire", "flame"],
  "ziemia": ["earth", "ground", "land"],
  "morze": ["sea", "ocean"],
  "rzeka": ["river", "stream"],
  "las": ["forest", "woods"],
  "góra": ["mountain", "hill"],
  "kwiat": ["flower", "blossom"],
  "zwierzę": ["animal", "creature"],
  "ptak": ["bird", "fowl"],
  "ryba": ["fish", "seafood"],
  "ciało": ["body", "flesh"],
  "głowa": ["head", "mind"],
  "ręka": ["hand", "arm"],
  "noga": ["leg", "foot"],
  "oko": ["eye", "sight"],
  "ucho": ["ear", "hearing"],
  "serce": ["heart", "soul"],
  "rodzina": ["family", "household"],
  "przyjaciel": ["friend", "buddy", "pal"],
  "dziecko": ["child", "kid"],
  "kobieta": ["woman", "lady"],
  "mężczyzna": ["man", "gentleman"],
  "ludzie": ["people", "folks"],
  "grupa": ["group", "team"],
  "telefon": ["phone", "telephone"],
  "komputer": ["computer", "PC"],
  "pokój": ["room", "peace"],

  // ===== A2 =====
  // Adjectives A2
  "możliwy": ["possible", "feasible"],
  "niemożliwy": ["impossible", "unfeasible"],
  "gotowy": ["ready", "prepared"],
  "pewny": ["sure", "certain", "confident"],
  "spokojny": ["calm", "peaceful", "quiet"],
  "zdenerwowany": ["nervous", "upset", "anxious"],
  "zadowolony": ["satisfied", "pleased", "content"],
  "rozczarowany": ["disappointed", "let down"],
  "samotny": ["lonely", "alone"],
  "wolny": ["slow", "free"],
  "zajęty": ["busy", "occupied"],
  "nudny": ["boring", "dull"],
  "ciekawy": ["interesting", "curious"],
  "wygodny": ["comfortable", "convenient"],
  "niewygodny": ["uncomfortable", "inconvenient"],
  "odpowiedni": ["appropriate", "suitable", "proper"],
  "nieodpowiedni": ["inappropriate", "unsuitable"],
  "dokładny": ["exact", "precise", "accurate"],
  "podobny": ["similar", "alike"],
  "różny": ["different", "various"],
  "popularny": ["popular", "well-known"],
  "znany": ["famous", "well-known"],
  "nieznany": ["unknown", "unfamiliar"],
  "bezpieczny": ["safe", "secure"],
  "niebezpieczny": ["dangerous", "hazardous", "unsafe"],
  "przyjemny": ["pleasant", "enjoyable"],
  "nieprzyjemny": ["unpleasant", "disagreeable"],
  "nowoczesny": ["modern", "contemporary"],
  "naturalny": ["natural", "organic"],
  "zwykły": ["ordinary", "usual", "common"],
  "specjalny": ["special", "particular"],
  "ogromny": ["huge", "enormous", "massive"],
  "malutki": ["tiny", "miniature"],
  "jasny": ["bright", "clear", "light"],
  "ciemny": ["dark", "dim"],
  "ostry": ["sharp", "spicy", "harsh"],
  "gładki": ["smooth", "sleek"],
  "twardy": ["hard", "tough", "firm"],
  "miękki": ["soft", "gentle"],
  "głęboki": ["deep", "profound"],
  "płytki": ["shallow", "superficial"],
  "stały": ["constant", "permanent", "steady"],
  "ścisły": ["strict", "precise", "exact"],
  "surowy": ["strict", "raw", "harsh"],
  "łagodny": ["gentle", "mild", "soft"],

  // Verbs A2
  "planować": ["plan", "schedule"],
  "decydować": ["decide", "determine"],
  "zgadzać się": ["agree", "consent"],
  "odmawiać": ["refuse", "decline", "reject"],
  "proponować": ["propose", "suggest", "offer"],
  "akceptować": ["accept", "approve"],
  "porównywać": ["compare", "contrast"],
  "opisywać": ["describe", "depict"],
  "wyjaśniać": ["explain", "clarify"],
  "tłumaczyć": ["translate", "explain"],
  "organizować": ["organize", "arrange"],
  "przygotowywać": ["prepare", "get ready"],
  "poprawiać": ["correct", "improve", "fix"],
  "niszczyć": ["destroy", "ruin"],
  "chronić": ["protect", "guard"],
  "kontrolować": ["control", "check", "monitor"],
  "obserwować": ["observe", "watch"],
  "sprawdzać": ["check", "verify", "inspect"],
  "używać": ["use", "utilize"],
  "włączać": ["turn on", "include", "switch on"],
  "wyłączać": ["turn off", "exclude", "switch off"],
  "dodawać": ["add", "include"],
  "odejmować": ["subtract", "deduct"],
  "dzielić": ["divide", "share", "split"],
  "łączyć": ["connect", "combine", "join"],
  "rozdzielać": ["separate", "divide"],
  "zbierać": ["collect", "gather"],
  "dostarczać": ["deliver", "provide", "supply"],
  "wysyłać": ["send", "ship", "dispatch"],
  "otrzymywać": ["receive", "get", "obtain"],
  "zapraszać": ["invite", "ask over"],
  "witać": ["greet", "welcome"],
  "żegnać": ["say goodbye", "bid farewell"],
  "martwić się": ["worry", "be concerned"],
  "bać się": ["be afraid", "fear"],
  "cieszyć się": ["enjoy", "be glad", "rejoice"],
  "denerwować się": ["be nervous", "get upset"],
  "wstydzić się": ["be ashamed", "be embarrassed"],
  "nudzić się": ["be bored", "get bored"],
  "spieszyć się": ["hurry", "rush", "be in a hurry"],
  "odpoczywać": ["rest", "relax"],
  "podróżować": ["travel", "journey"],
  "zwiedzać": ["sightsee", "explore", "tour"],
  "rezerwować": ["book", "reserve"],
  "pakować": ["pack", "wrap"],
  "przeprowadzać się": ["move", "relocate"],
  "naprawiać": ["repair", "fix", "mend"],
  "czyścić": ["clean", "cleanse"],
  "sprzątać": ["clean up", "tidy up"],
  "prać": ["wash", "do laundry"],
  "prasować": ["iron", "press"],
  "kroić": ["cut", "slice", "chop"],
  "smażyć": ["fry", "pan-fry"],
  "piec": ["bake", "roast"],
  "mieszać": ["mix", "stir", "blend"],
  "kosztować": ["cost", "taste"],
  "oszczędzać": ["save", "economize"],
  "wydawać": ["spend", "publish", "seem"],
  "pożyczać": ["borrow", "lend"],
  "inwestować": ["invest", "put money in"],
  "zarabiać": ["earn", "make money"],
  "zatrudniać": ["hire", "employ"],
  "zwalniać": ["fire", "dismiss", "slow down"],
  "awansować": ["promote", "advance"],
  "rezygnować": ["resign", "give up", "quit"],
  "konkurować": ["compete", "rival"],
  "współpracować": ["cooperate", "collaborate"],
  "przewodzić": ["lead", "guide"],
  "kierować": ["manage", "direct", "steer"],

  // Nouns A2
  "spotkanie": ["meeting", "appointment", "encounter"],
  "rozmowa": ["conversation", "talk", "discussion"],
  "wiadomość": ["message", "news"],
  "informacja": ["information", "data", "info"],
  "opinia": ["opinion", "view"],
  "rada": ["advice", "council", "tip"],
  "decyzja": ["decision", "choice"],
  "cel": ["goal", "aim", "target"],
  "plan": ["plan", "schedule"],
  "wynik": ["result", "score", "outcome"],
  "sukces": ["success", "achievement"],
  "porażka": ["failure", "defeat"],
  "doświadczenie": ["experience", "experiment"],
  "wiedza": ["knowledge", "expertise"],
  "umiejętność": ["skill", "ability"],
  "szansa": ["chance", "opportunity"],
  "ryzyko": ["risk", "danger"],
  "zasada": ["rule", "principle"],
  "prawo": ["law", "right"],
  "obowiązek": ["duty", "obligation"],
  "wolność": ["freedom", "liberty"],
  "bezpieczeństwo": ["safety", "security"],
  "zdrowie": ["health", "wellness"],
  "choroba": ["disease", "illness", "sickness"],
  "lek": ["medicine", "drug", "medication"],
  "ból": ["pain", "ache"],
  "nastrój": ["mood", "temper"],
  "uczucie": ["feeling", "emotion"],
  "miłość": ["love", "affection"],
  "przyjaźń": ["friendship", "companionship"],
  "związek": ["relationship", "connection"],
  "małżeństwo": ["marriage", "wedding"],
  "urodziny": ["birthday", "birth date"],
  "święto": ["holiday", "celebration", "festival"],
  "ceremonia": ["ceremony", "ritual"],
  "podróż": ["trip", "journey", "travel"],
  "wycieczka": ["excursion", "trip", "tour"],
  "wakacje": ["vacation", "holidays"],
  "lotnisko": ["airport", "airfield"],
  "dworzec": ["station", "terminal"],
  "przystanek": ["stop", "bus stop"],
  "bilet": ["ticket", "pass"],
  "bagaż": ["luggage", "baggage"],
  "kierunek": ["direction", "course"],
  "odległość": ["distance", "range"],
  "prędkość": ["speed", "velocity"],
  "ruch": ["movement", "traffic", "motion"],
  "wypadek": ["accident", "incident"],
  "napój": ["drink", "beverage"],
  "posiłek": ["meal", "dish"],
  "przepis": ["recipe", "regulation"],
  "smak": ["taste", "flavor"],
  "zapach": ["smell", "scent", "aroma"],
  "dźwięk": ["sound", "tone"],
  "hałas": ["noise", "racket"],
  "cisza": ["silence", "quiet"],
  "światło": ["light", "glow"],
  "cień": ["shadow", "shade"],
  "kształt": ["shape", "form"],
  "rozmiar": ["size", "dimension"],
  "waga": ["weight", "scale"],
  "materiał": ["material", "fabric"],
  "narzędzie": ["tool", "instrument"],
  "maszyna": ["machine", "engine"],
  "urządzenie": ["device", "appliance"],
  "firma": ["company", "firm", "business"],
  "biuro": ["office", "bureau"],
  "fabryka": ["factory", "plant"],
  "rynek": ["market", "marketplace"],
  "produkt": ["product", "item"],
  "usługa": ["service", "assistance"],
  "klient": ["client", "customer"],
  "umowa": ["contract", "agreement"],
  "rachunek": ["bill", "account", "invoice"],
  "podatek": ["tax", "levy"],
  "pensja": ["salary", "wage", "pay"],
  "zawód": ["profession", "occupation", "job"],
  "stanowisko": ["position", "post", "stance"],
  "środowisko": ["environment", "surroundings"],
  "przyroda": ["nature", "wildlife"],
  "klimat": ["climate", "atmosphere"],
  "powietrze": ["air", "atmosphere"],
  "energia": ["energy", "power"],
  "temperatura": ["temperature", "heat"],
};

let updated = 0;
let alreadyArray = 0;

for (const word of words) {
  const pl = word.pl;
  if (synonymsMap[pl] && (word.level === 'A1' || word.level === 'A2')) {
    word.en = synonymsMap[pl];
    updated++;
  } else if (typeof word.en === 'string') {
    word.en = [word.en];
  } else {
    alreadyArray++;
  }
}

fs.writeFileSync('./words.json', JSON.stringify(words, null, 2), 'utf-8');
console.log(`Done! Updated ${updated} words with synonyms, converted rest to arrays. ${alreadyArray} were already arrays.`);
