#!/usr/bin/env python3
"""Generate words.json with 1000 Polish-English vocabulary pairs."""
import json

words = [
    # === PODSTAWOWE RZECZOWNIKI (1-100) ===
    ("dom", "house"), ("kot", "cat"), ("pies", "dog"), ("woda", "water"), ("chleb", "bread"),
    ("mleko", "milk"), ("jabłko", "apple"), ("książka", "book"), ("stół", "table"), ("krzesło", "chair"),
    ("okno", "window"), ("drzwi", "door"), ("samochód", "car"), ("droga", "road"), ("ulica", "street"),
    ("miasto", "city"), ("wieś", "village"), ("szkoła", "school"), ("praca", "work"), ("pieniądze", "money"),
    ("czas", "time"), ("dzień", "day"), ("noc", "night"), ("rano", "morning"), ("wieczór", "evening"),
    ("rok", "year"), ("miesiąc", "month"), ("tydzień", "week"), ("godzina", "hour"), ("minuta", "minute"),
    ("człowiek", "human"), ("mężczyzna", "man"), ("kobieta", "woman"), ("dziecko", "child"), ("chłopiec", "boy"),
    ("dziewczyna", "girl"), ("przyjaciel", "friend"), ("rodzina", "family"), ("matka", "mother"), ("ojciec", "father"),
    ("syn", "son"), ("córka", "daughter"), ("brat", "brother"), ("siostra", "sister"), ("babcia", "grandmother"),
    ("dziadek", "grandfather"), ("mąż", "husband"), ("żona", "wife"), ("imię", "name"), ("głowa", "head"),
    ("ręka", "hand"), ("noga", "leg"), ("oko", "eye"), ("ucho", "ear"), ("nos", "nose"),
    ("usta", "mouth"), ("ząb", "tooth"), ("włosy", "hair"), ("serce", "heart"), ("krew", "blood"),
    ("słońce", "sun"), ("księżyc", "moon"), ("gwiazda", "star"), ("niebo", "sky"), ("ziemia", "earth"),
    ("ogień", "fire"), ("powietrze", "air"), ("las", "forest"), ("drzewo", "tree"), ("kwiat", "flower"),
    ("trawa", "grass"), ("rzeka", "river"), ("morze", "sea"), ("góra", "mountain"), ("deszcz", "rain"),
    ("śnieg", "snow"), ("wiatr", "wind"), ("chmura", "cloud"), ("kamień", "stone"), ("piasek", "sand"),
    ("klucz", "key"), ("telefon", "phone"), ("komputer", "computer"), ("telewizor", "television"), ("radio", "radio"),
    ("zegar", "clock"), ("lampa", "lamp"), ("łóżko", "bed"), ("poduszka", "pillow"), ("koc", "blanket"),
    ("kubek", "mug"), ("talerz", "plate"), ("nóż", "knife"), ("widelec", "fork"), ("łyżka", "spoon"),
    ("garnek", "pot"), ("butelka", "bottle"), ("szklanka", "glass"), ("torba", "bag"), ("parasol", "umbrella"),

    # === JEDZENIE I NAPOJE (101-180) ===
    ("mięso", "meat"), ("kurczak", "chicken"), ("ryba", "fish"), ("jajko", "egg"), ("ser", "cheese"),
    ("masło", "butter"), ("ryż", "rice"), ("makaron", "pasta"), ("ziemniak", "potato"), ("pomidor", "tomato"),
    ("ogórek", "cucumber"), ("marchew", "carrot"), ("cebula", "onion"), ("czosnek", "garlic"), ("sałata", "lettuce"),
    ("kapusta", "cabbage"), ("grzyb", "mushroom"), ("fasola", "bean"), ("groszek", "pea"), ("kukurydza", "corn"),
    ("banan", "banana"), ("pomarańcza", "orange"), ("cytryna", "lemon"), ("truskawka", "strawberry"), ("winogrono", "grape"),
    ("arbuz", "watermelon"), ("brzoskwinia", "peach"), ("gruszka", "pear"), ("śliwka", "plum"), ("wiśnia", "cherry"),
    ("herbata", "tea"), ("kawa", "coffee"), ("sok", "juice"), ("piwo", "beer"), ("wino", "wine"),
    ("zupa", "soup"), ("sól", "salt"), ("pieprz", "pepper"), ("cukier", "sugar"), ("mąka", "flour"),
    ("olej", "oil"), ("ocet", "vinegar"), ("miód", "honey"), ("dżem", "jam"), ("czekolada", "chocolate"),
    ("ciastko", "cookie"), ("ciasto", "cake"), ("lody", "ice cream"), ("kanapka", "sandwich"), ("pizza", "pizza"),
    ("śniadanie", "breakfast"), ("obiad", "lunch"), ("kolacja", "dinner"), ("przekąska", "snack"), ("deser", "dessert"),
    ("przepis", "recipe"), ("smak", "taste"), ("głód", "hunger"), ("pragnienie", "thirst"), ("dieta", "diet"),
    ("restauracja", "restaurant"), ("kelner", "waiter"), ("menu", "menu"), ("rachunek", "bill"), ("napiwek", "tip"),
    ("piekarnia", "bakery"), ("sklep", "shop"), ("rynek", "market"), ("koszyk", "basket"), ("kolejka", "queue"),
    ("kiełbasa", "sausage"), ("szynka", "ham"), ("bułka", "roll"), ("tost", "toast"), ("płatki", "cereal"),
    ("jogurt", "yogurt"), ("śmietana", "cream"), ("majonez", "mayonnaise"), ("musztarda", "mustard"), ("ketchup", "ketchup"),

    # === UBRANIA I WYGLĄD (181-230) ===
    ("koszula", "shirt"), ("spodnie", "trousers"), ("sukienka", "dress"), ("spódnica", "skirt"), ("kurtka", "jacket"),
    ("płaszcz", "coat"), ("sweter", "sweater"), ("bluza", "hoodie"), ("krawat", "tie"), ("czapka", "cap"),
    ("kapelusz", "hat"), ("rękawiczki", "gloves"), ("szalik", "scarf"), ("buty", "shoes"), ("skarpetki", "socks"),
    ("pasek", "belt"), ("torebka", "purse"), ("plecak", "backpack"), ("okulary", "glasses"), ("zegarek", "watch"),
    ("pierścionek", "ring"), ("kolczyki", "earrings"), ("naszyjnik", "necklace"), ("bransoletka", "bracelet"), ("biżuteria", "jewelry"),
    ("bielizna", "underwear"), ("piżama", "pajamas"), ("kostium", "costume"), ("mundur", "uniform"), ("garnitur", "suit"),
    ("materiał", "fabric"), ("bawełna", "cotton"), ("wełna", "wool"), ("jedwab", "silk"), ("skóra", "leather"),
    ("guzik", "button"), ("zamek", "zipper"), ("kieszeń", "pocket"), ("rozmiar", "size"), ("moda", "fashion"),
    ("kolor", "color"), ("czerwony", "red"), ("niebieski", "blue"), ("zielony", "green"), ("żółty", "yellow"),
    ("biały", "white"), ("czarny", "black"), ("szary", "gray"), ("brązowy", "brown"), ("różowy", "pink"),

    # === DOM I MIESZKANIE (231-300) ===
    ("mieszkanie", "apartment"), ("pokój", "room"), ("kuchnia", "kitchen"), ("łazienka", "bathroom"), ("sypialnia", "bedroom"),
    ("salon", "living room"), ("korytarz", "hallway"), ("garaż", "garage"), ("ogród", "garden"), ("balkon", "balcony"),
    ("piwnica", "basement"), ("strych", "attic"), ("dach", "roof"), ("ściana", "wall"), ("podłoga", "floor"),
    ("sufit", "ceiling"), ("schody", "stairs"), ("winda", "elevator"), ("płot", "fence"), ("brama", "gate"),
    ("prysznic", "shower"), ("wanna", "bathtub"), ("umywalka", "sink"), ("toaleta", "toilet"), ("lustro", "mirror"),
    ("ręcznik", "towel"), ("mydło", "soap"), ("szampon", "shampoo"), ("szczoteczka", "toothbrush"), ("pasta", "toothpaste"),
    ("pralka", "washing machine"), ("lodówka", "fridge"), ("piekarnik", "oven"), ("kuchenka", "stove"), ("zmywarka", "dishwasher"),
    ("odkurzacz", "vacuum cleaner"), ("żelazko", "iron"), ("szafa", "wardrobe"), ("półka", "shelf"), ("szuflada", "drawer"),
    ("dywan", "carpet"), ("zasłona", "curtain"), ("obraz", "painting"), ("wazon", "vase"), ("świeca", "candle"),
    ("meble", "furniture"), ("kanapa", "sofa"), ("fotel", "armchair"), ("biurko", "desk"), ("telewizja", "television"),
    ("gniazdko", "socket"), ("kontakt", "switch"), ("żarówka", "light bulb"), ("kaloryfer", "radiator"), ("klimatyzacja", "air conditioning"),
    ("remont", "renovation"), ("farba", "paint"), ("młotek", "hammer"), ("gwóźdź", "nail"), ("śrubokręt", "screwdriver"),
    ("klej", "glue"), ("taśma", "tape"), ("lina", "rope"), ("drut", "wire"), ("narzędzie", "tool"),
    ("zamek do drzwi", "lock"), ("dzwonek", "doorbell"), ("skrzynka", "mailbox"), ("śmietnik", "trash can"),

    # === PRACA I EDUKACJA (301-400) ===
    ("nauczyciel", "teacher"), ("uczeń", "student"), ("lekarz", "doctor"), ("pielęgniarka", "nurse"), ("prawnik", "lawyer"),
    ("inżynier", "engineer"), ("kucharz", "cook"), ("kierowca", "driver"), ("policjant", "policeman"), ("strażak", "firefighter"),
    ("sprzedawca", "seller"), ("artysta", "artist"), ("muzyk", "musician"), ("pisarz", "writer"), ("aktor", "actor"),
    ("dentysta", "dentist"), ("aptekarz", "pharmacist"), ("mechanik", "mechanic"), ("elektryk", "electrician"), ("hydraulik", "plumber"),
    ("fryzjer", "hairdresser"), ("programista", "programmer"), ("księgowy", "accountant"), ("architekt", "architect"), ("dziennikarz", "journalist"),
    ("biuro", "office"), ("fabryka", "factory"), ("szpital", "hospital"), ("apteka", "pharmacy"), ("biblioteka", "library"),
    ("uniwersytet", "university"), ("lekcja", "lesson"), ("egzamin", "exam"), ("ocena", "grade"), ("zadanie", "task"),
    ("projekt", "project"), ("spotkanie", "meeting"), ("rozmowa", "conversation"), ("prezentacja", "presentation"), ("raport", "report"),
    ("pensja", "salary"), ("umowa", "contract"), ("szef", "boss"), ("kolega", "colleague"), ("klient", "client"),
    ("firma", "company"), ("zawód", "profession"), ("doświadczenie", "experience"), ("kariera", "career"), ("awans", "promotion"),
    ("ołówek", "pencil"), ("długopis", "pen"), ("zeszyt", "notebook"), ("papier", "paper"), ("kartka", "sheet"),
    ("kreda", "chalk"), ("tablica", "board"), ("mapa", "map"), ("atlas", "atlas"), ("słownik", "dictionary"),
    ("matematyka", "mathematics"), ("fizyka", "physics"), ("chemia", "chemistry"), ("biologia", "biology"), ("historia", "history"),
    ("geografia", "geography"), ("język", "language"), ("literatura", "literature"), ("sztuka", "art"), ("muzyka", "music"),
    ("informatyka", "computer science"), ("ekonomia", "economics"), ("filozofia", "philosophy"), ("psychologia", "psychology"), ("prawo", "law"),
    ("wiedza", "knowledge"), ("nauka", "science"), ("badanie", "research"), ("teoria", "theory"), ("praktyka", "practice"),
    ("pytanie", "question"), ("odpowiedź", "answer"), ("błąd", "mistake"), ("sukces", "success"), ("porażka", "failure"),
    ("cel", "goal"), ("plan", "plan"), ("pomysł", "idea"), ("problem", "problem"), ("rozwiązanie", "solution"),
    ("zasada", "rule"), ("przykład", "example"), ("ćwiczenie", "exercise"), ("test", "test"), ("wynik", "result"),
    ("dyplom", "diploma"), ("certyfikat", "certificate"), ("stypendium", "scholarship"), ("urlop", "vacation"), ("emerytura", "retirement"),

    # === TRANSPORT I PODRÓŻE (401-470) ===
    ("samolot", "airplane"), ("pociąg", "train"), ("autobus", "bus"), ("rower", "bicycle"), ("motocykl", "motorcycle"),
    ("taksówka", "taxi"), ("tramwaj", "tram"), ("metro", "subway"), ("statek", "ship"), ("łódź", "boat"),
    ("lotnisko", "airport"), ("dworzec", "station"), ("przystanek", "stop"), ("bilet", "ticket"), ("paszport", "passport"),
    ("wiza", "visa"), ("walizka", "suitcase"), ("mapa", "map"), ("podróż", "journey"), ("wycieczka", "trip"),
    ("hotel", "hotel"), ("pokój hotelowy", "hotel room"), ("rezerwacja", "reservation"), ("recepcja", "reception"), ("bagaż", "luggage"),
    ("kierunek", "direction"), ("północ", "north"), ("południe", "south"), ("wschód", "east"), ("zachód", "west"),
    ("prawo", "right"), ("lewo", "left"), ("prosto", "straight"), ("skrzyżowanie", "crossroads"), ("most", "bridge"),
    ("tunel", "tunnel"), ("autostrada", "highway"), ("chodnik", "sidewalk"), ("parking", "parking"), ("stacja benzynowa", "gas station"),
    ("opona", "tire"), ("silnik", "engine"), ("hamulec", "brake"), ("kierownica", "steering wheel"), ("lusterko", "mirror"),
    ("paliwo", "fuel"), ("olej silnikowy", "engine oil"), ("prędkość", "speed"), ("wypadek", "accident"), ("mandat", "fine"),
    ("plaża", "beach"), ("wyspa", "island"), ("jezioro", "lake"), ("wodospad", "waterfall"), ("jaskinia", "cave"),
    ("zamek", "castle"), ("kościół", "church"), ("muzeum", "museum"), ("pomnik", "monument"), ("park", "park"),
    ("zoo", "zoo"), ("kino", "cinema"), ("teatr", "theater"), ("stadion", "stadium"), ("basen", "swimming pool"),
    ("granica", "border"), ("ambasada", "embassy"), ("obywatel", "citizen"), ("turysta", "tourist"), ("przewodnik", "guide"),

    # === ZDROWIE I CIAŁO (471-540) ===
    ("zdrowie", "health"), ("choroba", "disease"), ("ból", "pain"), ("gorączka", "fever"), ("kaszel", "cough"),
    ("katar", "runny nose"), ("grypa", "flu"), ("przeziębienie", "cold"), ("alergia", "allergy"), ("rana", "wound"),
    ("plaster", "bandage"), ("tabletka", "pill"), ("zastrzyk", "injection"), ("recepta", "prescription"), ("badanie", "examination"),
    ("operacja", "surgery"), ("szpital", "hospital"), ("karetka", "ambulance"), ("lekarz", "doctor"), ("pacjent", "patient"),
    ("ramię", "arm"), ("łokieć", "elbow"), ("nadgarstek", "wrist"), ("palec", "finger"), ("kciuk", "thumb"),
    ("kolano", "knee"), ("stopa", "foot"), ("kostka", "ankle"), ("plecy", "back"), ("brzuch", "stomach"),
    ("klatka piersiowa", "chest"), ("szyja", "neck"), ("czoło", "forehead"), ("policzek", "cheek"), ("broda", "chin"),
    ("brew", "eyebrow"), ("rzęsa", "eyelash"), ("powieka", "eyelid"), ("warga", "lip"), ("język", "tongue"),
    ("gardło", "throat"), ("płuco", "lung"), ("wątroba", "liver"), ("nerka", "kidney"), ("żołądek", "stomach"),
    ("mózg", "brain"), ("kość", "bone"), ("mięsień", "muscle"), ("skóra", "skin"), ("paznokieć", "fingernail"),
    ("wzrok", "sight"), ("słuch", "hearing"), ("dotyk", "touch"), ("smak", "taste"), ("węch", "smell"),
    ("sen", "sleep"), ("marzenie", "dream"), ("zmęczenie", "fatigue"), ("energia", "energy"), ("siła", "strength"),
    ("waga", "weight"), ("wzrost", "height"), ("tętno", "pulse"), ("ciśnienie", "pressure"), ("temperatura", "temperature"),

    # === UCZUCIA I EMOCJE (541-600) ===
    ("szczęście", "happiness"), ("smutek", "sadness"), ("złość", "anger"), ("strach", "fear"), ("zaskoczenie", "surprise"),
    ("miłość", "love"), ("nienawiść", "hatred"), ("radość", "joy"), ("nadzieja", "hope"), ("rozpacz", "despair"),
    ("duma", "pride"), ("wstyd", "shame"), ("zazdrość", "jealousy"), ("litość", "pity"), ("wdzięczność", "gratitude"),
    ("cierpliwość", "patience"), ("odwaga", "courage"), ("lenistwo", "laziness"), ("ciekawość", "curiosity"), ("nuda", "boredom"),
    ("spokój", "peace"), ("stres", "stress"), ("niepokój", "anxiety"), ("samotność", "loneliness"), ("tęsknota", "longing"),
    ("zaufanie", "trust"), ("szacunek", "respect"), ("troska", "care"), ("współczucie", "compassion"), ("przyjaźń", "friendship"),
    ("wesele", "wedding"), ("rozwód", "divorce"), ("kłótnia", "argument"), ("przeprosiny", "apology"), ("przebaczenie", "forgiveness"),
    ("obietnica", "promise"), ("tajemnica", "secret"), ("prawda", "truth"), ("kłamstwo", "lie"), ("żart", "joke"),
    ("uśmiech", "smile"), ("śmiech", "laughter"), ("płacz", "cry"), ("krzyk", "scream"), ("szept", "whisper"),
    ("pocałunek", "kiss"), ("uścisk", "hug"), ("gest", "gesture"), ("mina", "expression"), ("nastrój", "mood"),
    ("charakter", "character"), ("osobowość", "personality"), ("temperament", "temperament"), ("humor", "humor"), ("wrażliwość", "sensitivity"),
    ("pewność siebie", "confidence"), ("nieśmiałość", "shyness"), ("uprzejmość", "kindness"), ("okrucieństwo", "cruelty"), ("hojność", "generosity"),

    # === CZASOWNIKI (601-750) ===
    ("być", "be"), ("mieć", "have"), ("robić", "do"), ("iść", "go"), ("przychodzić", "come"),
    ("widzieć", "see"), ("słyszeć", "hear"), ("mówić", "speak"), ("czytać", "read"), ("pisać", "write"),
    ("jeść", "eat"), ("pić", "drink"), ("spać", "sleep"), ("budzić się", "wake up"), ("myć się", "wash"),
    ("ubierać się", "dress"), ("gotować", "cook"), ("sprzątać", "clean"), ("prać", "wash"), ("prasować", "iron"),
    ("kupować", "buy"), ("sprzedawać", "sell"), ("płacić", "pay"), ("zarabiać", "earn"), ("oszczędzać", "save"),
    ("dawać", "give"), ("brać", "take"), ("nosić", "carry"), ("kłaść", "put"), ("trzymać", "hold"),
    ("otwierać", "open"), ("zamykać", "close"), ("włączać", "turn on"), ("wyłączać", "turn off"), ("ciągnąć", "pull"),
    ("pchać", "push"), ("rzucać", "throw"), ("łapać", "catch"), ("ciąć", "cut"), ("łamać", "break"),
    ("budować", "build"), ("naprawiać", "repair"), ("niszczyć", "destroy"), ("tworzyć", "create"), ("rysować", "draw"),
    ("malować", "paint"), ("śpiewać", "sing"), ("tańczyć", "dance"), ("grać", "play"), ("biegać", "run"),
    ("chodzić", "walk"), ("skakać", "jump"), ("pływać", "swim"), ("latać", "fly"), ("jeździć", "ride"),
    ("prowadzić", "drive"), ("parkować", "park"), ("zatrzymać się", "stop"), ("czekać", "wait"), ("szukać", "search"),
    ("znajdować", "find"), ("tracić", "lose"), ("wygrywać", "win"), ("próbować", "try"), ("kończyć", "finish"),
    ("zaczynać", "start"), ("kontynuować", "continue"), ("powtarzać", "repeat"), ("zmieniać", "change"), ("wybierać", "choose"),
    ("decydować", "decide"), ("planować", "plan"), ("organizować", "organize"), ("pomagać", "help"), ("potrzebować", "need"),
    ("chcieć", "want"), ("lubić", "like"), ("kochać", "love"), ("nienawidzić", "hate"), ("preferować", "prefer"),
    ("wierzyć", "believe"), ("myśleć", "think"), ("wiedzieć", "know"), ("rozumieć", "understand"), ("pamiętać", "remember"),
    ("zapominać", "forget"), ("uczyć się", "learn"), ("uczyć", "teach"), ("studiować", "study"), ("tłumaczyć", "translate"),
    ("pytać", "ask"), ("odpowiadać", "answer"), ("dziękować", "thank"), ("przepraszać", "apologize"), ("zapraszać", "invite"),
    ("odwiedzać", "visit"), ("spotykać", "meet"), ("żegnać się", "say goodbye"), ("witać", "greet"), ("przedstawiać", "introduce"),
    ("dzwonić", "call"), ("wysyłać", "send"), ("otrzymywać", "receive"), ("dostarczać", "deliver"), ("zamawiać", "order"),
    ("rezerwować", "book"), ("anulować", "cancel"), ("potwierdzać", "confirm"), ("sprawdzać", "check"), ("porównywać", "compare"),
    ("liczyć", "count"), ("mierzyć", "measure"), ("ważyć", "weigh"), ("dodawać", "add"), ("odejmować", "subtract"),
    ("mnożyć", "multiply"), ("dzielić", "divide"), ("rosnąć", "grow"), ("spadać", "fall"), ("podnosić", "lift"),
    ("wstawać", "stand up"), ("siadać", "sit down"), ("leżeć", "lie down"), ("opierać się", "lean"), ("kucać", "squat"),
    ("oddychać", "breathe"), ("kichać", "sneeze"), ("ziewać", "yawn"), ("krzyczeć", "shout"), ("szeptać", "whisper"),
    ("obiecywać", "promise"), ("kłamać", "lie"), ("marzyć", "dream"), ("planować", "plan"), ("martwić się", "worry"),
    ("bać się", "be afraid"), ("cieszyć się", "enjoy"), ("nudzić się", "be bored"), ("denerwować się", "be nervous"), ("relaksować się", "relax"),
    ("śmiać się", "laugh"), ("płakać", "cry"), ("przytulać", "hug"), ("całować", "kiss"), ("machać", "wave"),

    # === PRZYMIOTNIKI (751-870) ===
    ("duży", "big"), ("mały", "small"), ("wysoki", "tall"), ("niski", "short"), ("długi", "long"),
    ("krótki", "short"), ("szeroki", "wide"), ("wąski", "narrow"), ("gruby", "thick"), ("cienki", "thin"),
    ("ciężki", "heavy"), ("lekki", "light"), ("szybki", "fast"), ("wolny", "slow"), ("nowy", "new"),
    ("stary", "old"), ("młody", "young"), ("dobry", "good"), ("zły", "bad"), ("ładny", "pretty"),
    ("brzydki", "ugly"), ("piękny", "beautiful"), ("silny", "strong"), ("słaby", "weak"), ("twardy", "hard"),
    ("miękki", "soft"), ("mokry", "wet"), ("suchy", "dry"), ("gorący", "hot"), ("zimny", "cold"),
    ("ciepły", "warm"), ("chłodny", "cool"), ("jasny", "bright"), ("ciemny", "dark"), ("głośny", "loud"),
    ("cichy", "quiet"), ("czysty", "clean"), ("brudny", "dirty"), ("pusty", "empty"), ("pełny", "full"),
    ("bogaty", "rich"), ("biedny", "poor"), ("drogi", "expensive"), ("tani", "cheap"), ("wolny", "free"),
    ("zajęty", "busy"), ("łatwy", "easy"), ("trudny", "difficult"), ("prosty", "simple"), ("skomplikowany", "complicated"),
    ("ważny", "important"), ("możliwy", "possible"), ("niemożliwy", "impossible"), ("konieczny", "necessary"), ("gotowy", "ready"),
    ("otwarty", "open"), ("zamknięty", "closed"), ("bezpieczny", "safe"), ("niebezpieczny", "dangerous"), ("zdrowy", "healthy"),
    ("chory", "sick"), ("zmęczony", "tired"), ("głodny", "hungry"), ("spragniony", "thirsty"), ("szczęśliwy", "happy"),
    ("smutny", "sad"), ("zły", "angry"), ("spokojny", "calm"), ("nerwowy", "nervous"), ("dumny", "proud"),
    ("pewny", "certain"), ("niepewny", "uncertain"), ("ciekawy", "interesting"), ("nudny", "boring"), ("zabawny", "funny"),
    ("poważny", "serious"), ("miły", "nice"), ("uprzejmy", "polite"), ("niegrzeczny", "rude"), ("uczciwy", "honest"),
    ("mądry", "wise"), ("głupi", "stupid"), ("odważny", "brave"), ("tchórzliwy", "cowardly"), ("leniwy", "lazy"),
    ("pracowity", "hardworking"), ("cierpliwy", "patient"), ("niecierpliwy", "impatient"), ("samodzielny", "independent"), ("odpowiedzialny", "responsible"),
    ("wspaniały", "wonderful"), ("okropny", "terrible"), ("doskonały", "perfect"), ("zwykły", "ordinary"), ("wyjątkowy", "exceptional"),
    ("podobny", "similar"), ("różny", "different"), ("jednakowy", "identical"), ("przeciwny", "opposite"), ("główny", "main"),
    ("pierwszy", "first"), ("ostatni", "last"), ("następny", "next"), ("poprzedni", "previous"), ("środkowy", "middle"),
    ("prawy", "right"), ("lewy", "left"), ("górny", "upper"), ("dolny", "lower"), ("wewnętrzny", "inner"),
    ("zewnętrzny", "outer"), ("blisko", "near"), ("daleko", "far"), ("głęboki", "deep"), ("płytki", "shallow"),
    ("okrągły", "round"), ("kwadratowy", "square"), ("ostry", "sharp"), ("tępy", "blunt"), ("gładki", "smooth"),

    # === LICZBY I CZAS (871-920) ===
    ("zero", "zero"), ("jeden", "one"), ("dwa", "two"), ("trzy", "three"), ("cztery", "four"),
    ("pięć", "five"), ("sześć", "six"), ("siedem", "seven"), ("osiem", "eight"), ("dziewięć", "nine"),
    ("dziesięć", "ten"), ("dwadzieścia", "twenty"), ("trzydzieści", "thirty"), ("czterdzieści", "forty"), ("pięćdziesiąt", "fifty"),
    ("sto", "hundred"), ("tysiąc", "thousand"), ("milion", "million"), ("połowa", "half"), ("ćwierć", "quarter"),
    ("poniedziałek", "Monday"), ("wtorek", "Tuesday"), ("środa", "Wednesday"), ("czwartek", "Thursday"), ("piątek", "Friday"),
    ("sobota", "Saturday"), ("niedziela", "Sunday"), ("styczeń", "January"), ("luty", "February"), ("marzec", "March"),
    ("kwiecień", "April"), ("maj", "May"), ("czerwiec", "June"), ("lipiec", "July"), ("sierpień", "August"),
    ("wrzesień", "September"), ("październik", "October"), ("listopad", "November"), ("grudzień", "December"), ("wiosna", "spring"),
    ("lato", "summer"), ("jesień", "autumn"), ("zima", "winter"), ("wczoraj", "yesterday"), ("dzisiaj", "today"),
    ("jutro", "tomorrow"), ("teraz", "now"), ("potem", "later"), ("zawsze", "always"), ("nigdy", "never"),

    # === TECHNOLOGIA I MEDIA (921-960) ===
    ("internet", "internet"), ("strona", "website"), ("hasło", "password"), ("email", "email"), ("wiadomość", "message"),
    ("zdjęcie", "photo"), ("film", "movie"), ("piosenka", "song"), ("gra", "game"), ("aplikacja", "application"),
    ("ekran", "screen"), ("klawiatura", "keyboard"), ("mysz", "mouse"), ("drukarka", "printer"), ("słuchawki", "headphones"),
    ("ładowarka", "charger"), ("bateria", "battery"), ("kabel", "cable"), ("wtyczka", "plug"), ("dane", "data"),
    ("plik", "file"), ("folder", "folder"), ("program", "program"), ("system", "system"), ("sieć", "network"),
    ("pobierać", "download"), ("przesyłać", "upload"), ("instalować", "install"), ("aktualizować", "update"), ("usuwać", "delete"),
    ("kopiować", "copy"), ("wklejać", "paste"), ("zapisywać", "save"), ("drukować", "print"), ("skanować", "scan"),
    ("wyszukiwać", "search"), ("logować się", "log in"), ("wylogować się", "log out"), ("udostępniać", "share"), ("blokować", "block"),

    # === POGODA I PRZYRODA (961-1000) ===
    ("pogoda", "weather"), ("temperatura", "temperature"), ("stopień", "degree"), ("prognoza", "forecast"), ("burza", "storm"),
    ("błyskawica", "lightning"), ("grzmot", "thunder"), ("tęcza", "rainbow"), ("mgła", "fog"), ("lód", "ice"),
    ("grad", "hail"), ("susza", "drought"), ("powódź", "flood"), ("trzęsienie ziemi", "earthquake"), ("wulkan", "volcano"),
    ("ocean", "ocean"), ("zatoka", "bay"), ("dolina", "valley"), ("pustynia", "desert"), ("dżungla", "jungle"),
    ("zwierzę", "animal"), ("ptak", "bird"), ("ryba", "fish"), ("owad", "insect"), ("motyl", "butterfly"),
    ("pszczoła", "bee"), ("mrówka", "ant"), ("pająk", "spider"), ("mysz", "mouse"), ("królik", "rabbit"),
    ("koń", "horse"), ("krowa", "cow"), ("świnia", "pig"), ("owca", "sheep"), ("koza", "goat"),
    ("kura", "hen"), ("kaczka", "duck"), ("wilk", "wolf"), ("niedźwiedź", "bear"), ("lis", "fox"),
    ("żaba", "frog"), ("wąż", "snake"), ("orzeł", "eagle"), ("rekin", "shark"), ("wieloryb", "whale"),
    ("słoń", "elephant"), ("tygrys", "tiger"), ("lew", "lion"), ("małpa", "monkey"), ("żyrafa", "giraffe"),
    ("pingwin", "penguin"),
]

result = [{"id": i+1, "pl": pl, "en": en} for i, (pl, en) in enumerate(words)]
with open("words.json", "w", encoding="utf-8") as f:
    json.dump(result, f, ensure_ascii=False, indent=2)

print(f"Generated {len(result)} words")
